apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: oracle
  KC_DB_URL: >
    jdbc:oracle:thin:@(DESCRIPTION=
      (RETRY_COUNT=20)
      (RETRY_DELAY=3)
      (ADDRESS=(PROTOCOL=TCPS)(PORT=1522)(HOST=adb.eu-amsterdam-1.oraclecloud.com))
      (CONNECT_DATA=(SERVICE_NAME=g49f31b19d33266_keycloakauth_high.adb.oraclecloud.com))
      (SECURITY=(SSL_SERVER_DN_MATCH=YES))
    )

  KC_DB_USERNAME: keycloak_user
  KC_HOSTNAME: talentlink-erfan.nl
  KC_HOSTNAME_PATH: /auth
  KC_PROXY: edge
