apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /opt/keycloak/data || true"]
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args:
            - start
            - --db=postgres
            - --http-enabled=true
            - --http-port=8080
            - --hostname-strict=false
            - --hostname=talentlink-erfan.nl
            - --proxy-headers=xforwarded
            - --db-url=jdbc:postgresql://keycloak-db-postgresql:5432/keycloak
            - --db-username=keycloak
            - --db-password=StrongPassword123
          envFrom:
            - secretRef:
                name: keycloak-admin
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi