apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args:
            - start-dev
            - --http-relative-path=/keycloak
            - --proxy=edge
            - --hostname-strict=false
          envFrom:
            - secretRef:
                name: keycloak-admin
          env:
            - name: KC_HOSTNAME
              value: talentlink-erfan.nl
            - name: KC_PROXY_HEADERS
              value: xforwarded
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /keycloak/health/ready
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /keycloak/health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
