apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: change-me

  KC_DB: oracle
  KC_DB_USERNAME: keycloak_user
  KC_DB_PASSWORD: Keycloak123!

  KC_DB_URL: "jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.eu-amsterdam-1.oraclecloud.com))(connect_data=(service_name=g49f31b19d33266_keycloakauth_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"
