apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talentlink-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - talentlink-erfan.nl
      secretName: myapp-tls

  rules:
    - host: talentlink-erfan.nl
      http:
        paths:
          # FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # BACKEND MICROSERVICES (regex paths)
          - path: /api/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 5000

          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 5000

          - path: /api/jobs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: job-service
                port:
                  number: 5000

          - path: /api/cv(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cv-service
                port:
                  number: 5000

          - path: /api/matching(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: matching-service
                port:
                  number: 5000

          - path: /api/notifications(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-service
                port:
                  number: 5000

          # KEYCLOAK
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
