name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1' # match your cluster version

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy manifests
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/ --validate=false
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/backend
