name: Test OKE Connection

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  test-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          pip install --upgrade pip
          pip install oci-cli
          oci --version

      - name: Configure OCI CLI
        run: |
          mkdir -p $HOME/.oci
          echo "${{ secrets.OCI_CONFIG }}" | base64 --decode > $HOME/.oci/config
          echo "${{ secrets.OCI_KEY }}" | base64 --decode > $HOME/.oci/oci_api_key.pem
          chmod 600 $HOME/.oci/oci_api_key.pem

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Test cluster access
        run: |
          oci iam region list
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A
