name: Test OKE Connection

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  test-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- -b /usr/local/bin
          oci --version

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Test cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

