name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults --install-dir /usr/local/bin
          oci --version

      - name: Configure OCI CLI
        run: |
          mkdir -p $HOME/.oci
          echo "${{ secrets.OCI_CONFIG }}" > $HOME/.oci/config
          echo "${{ secrets.OCI-API_KEY }}" > $HOME/.oci/oci_api_key.pem
          chmod 600 $HOME/.oci/config $HOME/.oci/oci_api_key.pem

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.1'

      - name: Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > kubeconfig
          mkdir -p $HOME/.kube
          mv kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Cluster
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/backend
